apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: dev-cluster

spec:
    interval: 10m
    path: ./manifests
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
