apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: aws-ebs-csi-driver
    namespace: kube-system
spec:
    interval: 10m
    chart:
        spec:
            chart: aws-ebs-csi-driver
            version: "2.41.0" # Use the latest version compatible with your cluster (as of March 2025)
            sourceRef:
                kind: HelmRepository
                name: aws-ebs-csi-driver
                namespace: flux-system
            interval: 10m
    values:
        controller:
            serviceAccount:
                create: true
                name: ebs-csi-controller-sa
                annotations:
                    eks.amazonaws.com/role-arn: "arn:aws:iam::214259409527:role/EKS_EBS_CSI_DriverRole"
        storageClasses:
            - name: gp3
              annotations:
                  storageclass.kubernetes.io/is-default-class: "true"
              parameters:
                  type: gp3
                  fsType: ext4
              volumeBindingMode: WaitForFirstConsumer
              allowVolumeExpansion: true
            - name: gp2
              parameters:
                  type: gp2
                  fsType: ext4
              volumeBindingMode: WaitForFirstConsumer
              allowVolumeExpansion: true
