apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../../hello-world-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    service:
      type: LoadBalancer