# clusters/dev-cluster/flux-system/manifests/kube-prometheus-stack-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 10m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: "70.2.1" # Use the latest compatible version (e.g., 51.1.0 as of March 2025)
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: flux-system
            interval: 10m
    values:
        prometheus:
            prometheusSpec:
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: gp3 # Use the appropriate EKS storage class (e.g., gp2 or gp3)
                            accessModes: ["ReadWriteOnce"]
                            resources:
                                requests:
                                    storage: 8Gi
        grafana:
            adminPassword: "admin1234" # Set a custom admin password for Grafana
            persistence:
                enabled: true
                storageClassName: gp3
                accessModes: ["ReadWriteOnce"]
                size: 5Gi
